from utils import chatgpt, selenium, xi_labs
import json
import os

# cache/
#       problems: scraped from the web
#       generated_text: generated by OpenAI
#       audio: generated by Eleven Labs
#       data: final dict

def main():
    # Ctrl + F and search `cfg` to check variables
    with open("config.json", 'r', encoding='utf-8') as f:
        cfg = json.load(f)

    # When developing, choose gpt-4-1106-preview instead of gpt-4o

    output = {}

    # Scraping
    title, title_slug, description, example, example_dict, num, difficulty = selenium.scrape()
    output["title"] = title
    output["title_slug"] = title_slug
    output["number"] = num
    output["difficulty"] = difficulty
    output["description"] = description
    output["example"] = example_dict

    sections = {}
    # Thumbnail audio
    if cfg["thumbnail_audio"]:
        audio_thumbnail = input("Enter thumbnail title: ")
        sections["title"] = audio_thumbnail + ". "
    else:
        sections["title"] = f"LeetCode Problem {num}: " + title + ". "

    # Retrieving solution
    solution_path = f"cache/solution/{title_slug}.txt"
    if os.path.exists(solution_path):
        with open(solution_path, 'r', encoding='utf-8') as f:
            solution = f.read()
    else:
        solution = ""

    # Prompting
    print(f"\nGenerating prompt using {cfg["gen_model"]}...")
    response = ""
    prompt = chatgpt.generate_prompt(description, example, solution, language=cfg["language"])
    gen_path = f"cache/generated-text/{title_slug}.txt"
    if os.path.exists(gen_path) and cfg["reuse_prompt"]:
        with open(gen_path, 'r', encoding='utf-8') as f:
            response = f.read()
    else:
        response = chatgpt.complete_chat(prompt, cfg["gen_model"], title_slug)

    postprocessed_dict = chatgpt.postprocessing(response)
    for key, value in postprocessed_dict.items():
        sections[key] = value

    # Text to speech
    output["audio"] = {}
    code = ""
    script = ""
    
    for key, value in sections.items():
        if key != "solution":
            script += value
        else:
            code = value

    output["script"] = script
    
    # Script audio path
    print("\nGenerating audio...")
    audio_path = f"cache/audio/{title_slug}.mp3"
    if not (os.path.exists(audio_path) and cfg["reuse_audio"]):
        xi_labs.xi_tts(script, audio_path)
    output["audio"]["script"] = audio_path

    # Solution audio path
    solution_path = f"cache/audio/solution_{cfg["language"]}.mp3"
    if not os.path.exists(solution_path):
        xi_labs.xi_tts(f"Here's the solution written in {cfg["language"]}.", solution_path)
    output["audio"]["solution"] = solution_path

    # Background music path
    background_path = f"cache/audio/happy-bg-1.mp3"
    output["audio"]["background"] = background_path

    # Speech to timestamp
    print("\nGetting timestamps for audio...")
    output["timestamps"] = chatgpt.get_timestamps(output["audio"]["script"], cfg["stt_model"])

    # Cache
    if not os.path.exists("cache/data"):
        os.makedirs("cache/data")

    cache_path = f"cache/data/{title_slug}.json"
    with open(cache_path, "w") as f:
        json.dump(output, f, indent=4)
    print(f"\nResults saved in {cache_path}")
    
if __name__ == "__main__":
    main()